apiVersion: v1
kind: Namespace
metadata:
  name: yugabyte
  labels:
    app: yugabyte
  annotations:
    linkerd.io/inject: enabled
    field.cattle.io/projectId: local:applications
    scheduler.alpha.kubernetes.io/node-selector: "dedicated=etcd-node"